---
stages:
- name: BUILD
  inputs:
  - service: ${REPO}
    type: git
    branch: initial-cf
  triggers:
  - type: commit
  properties:
  - name: SUFFIX
    value: ${SUFFIX}
    type: text
  jobs:
  - name: Build LightBlueCompute Webapp
    type: builder
    build_type: shell
    script: |-
        #!/bin/bash
        # Configure config/default.json to include SUFFIX
        echo "Modify configurations for $SUFFIX"
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build LightBlueCompute Webapp
  triggers:
  - type: stage
  properties:
  - name: SUFFIX
    value: ${SUFFIX}
    type: text
  - name: APP_NAME
    value: lightblue-web-${SUFFIX}
    type: text
  jobs:
  - name: Deploy LightBlueCompute Webapp
    type: deployer
    deploy_permission: DEV_IN_SPACE
    target:
      region_id: ibm:yp:eu-gb
      organization: ${ORG}
      space: ${SPACE}
      application: ${APP_NAME}
    script: |
      #!/bin/bash
      cf push $APP_NAME -n $APP_NAME
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.eu-gb.bluemix.net/v1/messaging/webhook/publish

